const express = require('express')
const router = express.Router()
const properties = require('../../Controller/Properties/propertiesController')
const updateProperty = require('../../Controller/Properties/UpdateProperty')
const jwtVerify = require('../../Controller/JwtVerify/JwtVerify')

router.post('/post/propertyImages', jwtVerify, properties.imageUpload)
router.post('/post/propertyInfo', jwtVerify, properties.postProperty)
router.get('/get/allProperties', properties.getAllProperties)
router.get('/get/property/city/:id', properties.getPropertyByCity)
router.get('/get/property/address/:id', properties.getPropertyByAddress)
router.get('/get/user/properties/:id', jwtVerify, properties.getPropertyByUserId)
router.delete('/delete/property/:id', jwtVerify, properties.deleteProperty)
router.put('/update/property/:id', jwtVerify, updateProperty)
module.exports = router
