const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const cors = require('cors')
const properties = require('./src/Router/Properties/properties')
const users = require('./src/Router/Users/Users')
const favorties = require('./src/Router/Favorties/Favorties')
const emails = require('./src/Router/SendEmail/sendEmail')
const newsLetters = require('./src/Router/NewsLetters/NewsLetter')
require('dotenv').config()

app.use(express.json())
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))
app.use(cors())

app.use('/api', properties)
app.use('/api', users)
app.use('/api', favorties)
app.use('/api', emails)
app.use('/api', newsLetters)
const PORT = process.env.PORT || 3001
app.listen(PORT, (e) => e ? console.log(e) : console.log(`successfully connected to ${PORT}`))
