const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const cors = require('cors')
const properties = require('./Router/Properties/properties')
const users = require('./Router/Users/Users')
const favorties = require('./Router/Favorties/favorties')
const emails = require('./Router/SendEmail/sendEmail')
app.use(express.json())
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))
app.use(cors())

// router
app.use('/api', properties)
app.use('/api', users)
app.use('/api', favorties)
app.use('/api', emails)
const PORT = process.env.PORT || 3001
app.listen(PORT, (e) => e ? console.log(e) : console.log(`successfully connected to ${PORT}`))
